### ISSUE TITLE
Perceivable latency

### ISSUE THREAD

**Issue by franktinsley** [jasarien/Provenance#157]
For me, perceivable latency really kills the experience so it's my number one issue. I'm a humble C# Unity dev but if someone can point me in some kind of direction on where I might start I will do anything I can to try to help get latency down. I would love to see latency reduced to the point where we can all play Mario at least as well as we can on Mario Maker for Wii U (which manages to have remarkably low latency even through a wireless gamepad that's also receiving a video stream!)

**Comment by franktinsley** [comment]
So I think I'm going to focus all my efforts on making PRs for Provenance's UI and in exchange hope someone with skills can try to reduce latency. I have a feeling, since Provenance is apparently based on OpenEMU, that OpenEMU is where latency will really have to be solved.

**Comment by kreeger** [comment]
By perceivable latency, are you referring to button-press latency on the Apple TV with a third-party controller? Or just emulation latency across the whole application?

**Comment by fdotg** [comment]
I have noticeable latency on my appletv and the nimbus controller.

**Comment by dougnukem** [comment]
Have you tried turning down the D-Pad/Analog threshold from 50% to 0% that seemed to fix it for me. I was really only noticing latency in the D-Pad or Joystick, normal button presses seemed fine.

**Comment by tmolling** [comment]
I have a latency too when using the Nimbus controller on appletv (feels like 100-200ms. ). It does not seem to be limited to the d-pad since i experience it a lot in Super Mario when jumping using "a/b"-buttons.

**Comment by kreeger** [comment]
For me and my Nimbus controller on the Apple TV, it's not D-pad latency that I've noticed — it's button presses as well, across all games and emulation cores. Pairing the same controller with my iPad or iPhone doesn't produce any noticeable latency at all — so I'm seeing the same as @tmolling.

I'm happy to run this tethered to my Apple TV to help diagnose this. I tried to throw in some logging myself this past weekend to figure out where the disconnect is, but I didn't get very far. Logging happens right away when the button presses are sent to the various core-specific gamepad controllers, but once the emulation code receives the button press, it seems to be a 100-200ms delay before the press is registered on screen.

And this latency doesn't happen in the selection menu, nor does it happen with any other game. I wonder if it's an Apple TV processing timing issue? (I'm shooting from the hip now.)

**Comment by XeresRazor** [comment]
The lag may very well be TV related, most modern televisions have a delay due to the image processing they perform, something that doesn't occur on an iOS device. You might try checking the settings for your TV to see if it has a game mode that will reduce this delay.

**Comment by tmolling** [comment]
Dont think it's TV-related as I tried it on my main Television as well as hooking up the AppleTV on a computer screen with HDMI. Same result.

**Comment by jasarien** [comment]
@kreeger mentions that it doesn't happen on iOS, only tvOS? Then that would suggest some issue with the AppleTV itself and not Provenance?

**Comment by hambly** [comment]
I did some diagnostics today with regards to MFI controller input lag. I used both a Mad Catz Ctrl i Micro, and a Steel Series Stratus with both and Apple TV and iPhone 6s+.  The input latency is specific to Provenance/Emulators on the Apple TV only.

1) Provenance Apple TV  - both controllers have the same input lag, it's just bad enough to ruin the gameplay.  Someone above mentioned 200ms, and that probably makes sense from what I was experiencing. Tested on a couple SNES games.
2) Native Apple TV Apps - no noticeable lag with either controller.  Tested playing Transistor with both controllers.
3) Provenance on iPhone - no lag, tested on the same SNES games

**Comment by dougnukem** [comment]
Testing this and trying to put in some time elapsed logs, it's starting to feel like it might just be the Steel Series Stratus controller buttons themselves.

I tested on iOS and on tvos and the lag felt the same to me (felt like 200ms or so on SNES Super Mario world when I hit the A or B buttons). 

The D-Pad doesn't seem to have any latency once I dropped the D-Pad threshold to 0%.

What it feels like is that the Steel Series A, B, X, Y buttons are hard to register for a press you have to fully depress them and then it springs back up and it feels like it's a lot less smooth than a PS4 controller (or even a standard NES controller). 

I'm starting to think it's not really an input lag issue with MFI Controller on TVos but just sluggish mechanical buttons.

**Comment by dougnukem** [comment]
hmm I'm not quite sure though I just played Rayman and everything feels really responsive.

**Comment by jasarien** [comment]
Interested to know if anyone here experiencing latency has their Apple TV directly connected to the TV via HDMI, or has it running through a receiver or Xbox One's HDMI-In or similar?

I have mine running through my Xbox One's HDMI-In and I get some latency from that. Without the Xbox in the middle it feels fine.

**Comment by marlinmayo27** [comment]
My Apple TV is directly connected to my TV via HDMI and I have latency issues with both the D-pad and regular button presses. Very noticeable in Mario games. I just got the Nimbus controller today and only tested it out for about 5 minutes.

**Comment by hambly** [comment]
I'm connected directly from AppleTV to the TV's HDMI-In, and experiencing the latency with Provenance-TV only. Native apple tv games are OK, as is Provenance-iPhone.

I'll dig into the controller interface code and see if I can do some helpful profiling if I get a chance over the next few days.

**Comment by kreeger** [comment]
My experiences exactly are the same as @hambly's — I'm plugging right into my Vizio TV's HDMI port here, and I don't notice the same lag on Provenance-iPhone, nor any lag on other Apple TV games.

**Comment by kaikai1234** [comment]
as all mfi controllers have pressure sensitive buttons, maybe having deadzone settings for all buttons might help.

**Comment by jasarien** [comment]
There aren't any artificial dead zones added to other buttons. They use the '-pressed' method from the game controller framework to decide when they are pressed. The documentation states that this takes into account any kind of hardware deadzone from the manufacturers side.

**Comment by mattstocum** [comment]
I'm experiencing latency too, but similar to what I see in some games. Alto's Adventure has very similar latency with button presses. Canabalt, on the other hand, has zero perceivable latency. I'm wondering if the heuristic tvOS is using to determine button presses is just bad.

**Comment by jasarien** [comment]
I'm beginning to wonder if the paradigm Provenance is using for controller input is wrong...

All of the emulators used in Provenance work on the basis of polling for user input. Each iteration of the emulation loop, the emulator checks its controller representations to see which buttons are pressed at that point in time.

Meanwhile, provenance is working with an event-listening model for the MFi controllers, assigning a handler to each button and updating the controller state once a button is pressed.

I think this might lead to some sync issues between the controller and the emulator, where the input is out of sync with what is being displayed on screen.

it might be difficult to explain, but I'll try anyway:

Consider Mario on the NES as an example. The emulation loop executes and renders a frame of the game with an enemy close to Mario that would prompt the player to jump in order to avoid the enemy. Upon seeing this frame on the screen, the player would press the jump button. Here's where things get complicated. I think the emulation loop executes faster than the event processing loop for the app, and by extension, the game controller framework. So by the time the event handler for the button has been called and updated the controller state for the emulator, the emulator has already rendered a few more frames, before seeing that the button was pressed, and making Mario jump.

I'll experiment with this theory to see if I'm right, and if I am, then I'll need to rewrite the controller handling so that the emulator can query the input state directly from the controller itself.

**Comment by rreinhardt** [comment]
Hi @jasarien 

Another way to reproduce something that would be indicative of your theory is to rapidly press the jump button, say under a unlimited coin [?] box... If you do it fast enough you can witness certain jumps being 'dropped' which wouldn't happen if the game was in sync with the controller.

**Comment by whitverj** [comment]
Just wanted to leave a "Me too!" for latency on the Apple TV using a SteelSeries Nimbus.  I've turned all the processing options off on my TV and enabled gaming mode, so I'm sure that's not the cause.  It's not just the D-pad, it's all the buttons, and the delay is just enough that it's nigh-impossible to successfully play a game.

**Comment by kaikai1234** [comment]
@jasarien correct me if im wrong but your theory does not explain why some people here are claiming they are getting no lag when using a controller on the iPhone but getting lag on apple tv. anyone here who has a iPhone 6 and a Lightning Digital AV Adapter should try it on the same tv as their apple tv so we can eliminate tv lag as the culprit. i dont have a iphone but have a ipad 2 and that has a lot more lag then my apple tv.

**Comment by jasarien** [comment]
I don't know, maybe the different Sync rates have an effect?

**Comment by jasarien** [comment]
Should be fixed by 9bdd377f0530ac64b2c420fcb9ea97715762c576

Test it out and let me know if it feels better.

**Comment by kreeger** [comment]
Thanks for your work on this, @jasarien — I'm gonna check this out when I get home today.

**Comment by drewbaumann** [comment]
I still seem to still be experiencing lag (enough to hinder gameplay) on the Apple TV. I am using a steel series stratus and experimented on the NES and SNES emulator.

**Comment by kaikai1234** [comment]
i see no difference in latency,in fact i seem to be seeing a lot more with latest update, I'm going install a old version and check if im correct. jasarien i think you should try out a game like mario world, to see how bad it is.

**Comment by dougnukem** [comment]
I'm still seeing it as well.

Is there some way we could measure or print log the latency, I tried logging at the button press but I couldn't figure out where the internal SNES emulator actually handled the press state.

**Comment by hambly** [comment]
Tested on two apple tv's with two controllers (Stratus & Micro CTRLi) with a variety of games, definitely still enough latency with the controllers to make certain games unplayable (such as Super Mario World or Contra).

**Comment by whitverj** [comment]
I'm wondering if there's a simple way to just have a dot or something appear on screen when it registers an A,B,X,Y button press, just so we can nail down if the latency is from the time we press the button until Provenance registers it, or if it's downstream from that.

**Comment by kaikai1234** [comment]
ok did a full restart on the apple tv the horrible lag i was getting before is gone, the new version is better but there is still noticeable lag.

**Comment by bvleur** [comment]
Have to confirm the above. With tvOS 9.0.1 and the SteelSeries Nimbus controller and a build with 9bdd377f0530ac64b2c420fcb9ea97715762c576 included I see much less lag, but there still is some.

**Comment by mattstocum** [comment]
Still seeing latency here too on Super Mario World.

**Comment by tmolling** [comment]
Same here. No real change on NES/SMB. Latency is still pretty much the same and some button presses are not even registered. i.e. when holding A to run and then pressing B to jump, the jump sometimes is not made.

**Comment by jasarien** [comment]
Dunno what to say. It worked fine for me when I tested it, latency was much improved. I wouldn't have committed the changes had it made it worse. And there's so many mixed reports here that I can't draw any useful conclusions. Some people say it's better, some say it's the same, others say it's worse. Some say rebooting their AppleTV fixes some latency issues. Have you tried that? Have you tried re-pairing your controller to eliminate any bluetooth issues?

**Comment by drcreek** [comment]
I've just connected a brand new controller to the latest build. Freshly rebooted. Controller is very quick and responsive when controlling the UI. But in games. It's laggy in a way that is just enough to suck all the joy out of it. The Genesis and Master System emulators seems faster than SNES. but both lag. Just the SNES lags a little more.

**Comment by chriscthompson** [comment]
Ok I've been watching this thread for a while and I have to chime in...

I'm using release version 1.2.2 with a Nimbus Controller on a 32 GB   TV 4 and I have next to zero or an imperceptible lag if there is any at all. My son also has the exact same experience on his with the identical setup.

No lag in SNES Super Mario World or Genesis Sonic & Knuckles

**Comment by jasarien** [comment]
@chriscthompson 1.2.2 is a few versions behind the current. Could you try with the latest build?

**Comment by chriscthompson** [comment]
Yes. I can update tonight and let you know my feedback.

**Comment by tmolling** [comment]
Looks like this is gonna be a neverending story :P 

well, i tested again: apple tv rebooted, provenance 1.2.6, Nimbus re-paired, controller is very close to the aTV, but it still lags.

Here the result: https://vid.me/30Z7

tbn. i've tested with the aTV remote as controller, an the lag is identical. so the nimbus can be excluded as root cause.

**Comment by jasarien** [comment]
@tmolling Does your TV have a "game-mode" and is it enabled?

**Comment by tmolling** [comment]
yes, gaming-mode is turned on. tested on a samsung tv, which does not feature a gaming mode, but same lag.

**Comment by drcreek** [comment]
Just to add. It's not my TV at least. Game mode on.  I have the same lag as in the video. But the controller is almost instant on Crossy road. And that is a twitchers game.

Skickat från min iPhone

**Comment by franktinsley** [comment]
With latency being a huge problem for OpenEMU is there some reason Provenence should be expected to improve on it?

Also a very simple way to test a setup and verify that the latency is coming from Provenence and no where else is to simply test other games that use mfi controllers on the same Apple TV.

**Comment by kreeger** [comment]
@franktinsley The issue seems to be specific to the combination of Apple TV + Provenance + MFi controllers. We've tested for controller latency on other Apple TV games (Badland, Canabalt, etc.) and there doesn't seem to be any latency with those.

Likewise, using the same MFi controller with the same build of Provenance on an iPad or iPhone doesn't yield any latency there, either. I wouldn't strike OpenEMU off the list as being a problem, but latency does seem to be just fine on iOS. It's just on tvOS that seems to be an issue.

**Comment by drcreek** [comment]
Also. I have noticed the lag is much much lower with the Apple Remote. 

MFi controller. It's not playable for most games.

**Comment by jasarien** [comment]
There is way too much conflicting information in this issue. Some people say they experience latency, others do not. Everyone has different configs and setups, different hardware. No-one has done a controlled experiment with a Test ROM designed to measure latency, no-one has wired up an LED to the controller button and taken High-FPS video (and I mean not iPhone camera footage) to capture when the LED lights and the Test ROM shows the button press.

I appreciate you may feel like you have latency issues, but with so many variables (bluetooth, different models of TV, different controllers, different connections, different games), it's impossible to know empirically where that latency may be coming from, whether it's Provenance, the individual ROMs, the hardware, the wireless connection. etc.

**Comment by jasarien** [comment]
I'm unlocking the comments here, since I've had some reports that iOS 9.1 has improved the latency issues some were experiencing with MFi controllers on tvOS. If you could test it and report back, I'd be interested to hear.

**Comment by kreeger** [comment]
Gladly. Do I need to recompile against the tvOS 9.1 SDK first?

**Comment by jasarien** [comment]
I don't think so - the reports are saying all they did is update to 9.1 on their Apple TV, they didn't recompile/reinstall Provenance.

**Comment by kreeger** [comment]
Sadly I don't see any change in button press latency. I've tested with both Super Mario Bros. for NES and Mega Man X for SNES. It appears to be the same as it was after you made the change for polling for presses.

**Comment by jasarien** [comment]
yeah I thought it would be a bit too good to be true.

**Comment by graphicbryan** [comment]
I'll upload my settings later, but I was very surprised how much better the latency issues were after 9.1 update.

**Comment by bvleur** [comment]
Sadly I have to confirm no real improvements for me too.

Tested Steelseries Nimbus with Apple TV 4 on tvOS 9.1 with a Release build with the polling code.

I've compared the perceived latency with Super Mario World on the real SNES on the same TV (while not ruling it out completely due to HDMI versus composite)

Also I've played other games with the same controller on the same TV and Apple TV where I feel there is less latency.

If you need any help getting the required equipment to test this out yourself, please let us know. I guess a donation campaign would go pretty far :) I really appreciate your work on this project!

**Comment by graphicbryan** [comment]
Tested:
SteelSeries Nimbus & Horipad Ultimate w/ATV4 9.1, running Providence Release Build 1.2.6 (no additional mods) straight HDMI to Panasonic Plasma (game mode off), both controllers appear to be working with very low if any latency (for just about all EMUs). The other variable, is that testing was done later at night when many radio frequencies are at an all time low, so could have affected things.

I'll do more experimenting tonight when I get time. See if this performance improvement sticks or not.

**Comment by drewbaumann** [comment]
@graphicbryan I just picked up a nimbus as well, but have only tested on my iPad. Is it still working great with your ATV?

**Comment by pjpalomaki** [comment]
Mine works great on ATV 4. I don't really notice much/any latency..

**Comment by pjpalomaki** [comment]
Just had a little go again after playing on PC with Xbox 360 controller (wireless) and yes, there is some lag with Ninbus+ATV4..

**Comment by graphicbryan** [comment]
@drewbaumann with build 1.2.6 and tvOS 9.1 things still appear to be working well with my preferred controller the horipad ultimate. I'm sure the nimbus is good too, but like the feel of the hori more. Lag is there on some games, but it's in the code of the game not the emu if I remember correctly.

**Comment by whitverj** [comment]
If it were in the code of the game, then the lag would be there whether playing on AppleTV or on iPad/iPhone, which (as others have determined) is not the case.  iPhone/iPad seems lag-free in all cases, it's only AppleTV which has the issue this bug is trying to address.

**Comment by graphicbryan** [comment]
@whitverj that is correct, I will have to check other devices with emu and the games in question, but the lag that I'm noticing was on original NES consul too (at least I'm pretty sure, been a few years)

**Comment by sakuranbokun** [comment]
I'll chime in with my experiences - I'm using a Horipad with my ATV, and it's connected via an AV amp to a Pioneer Kuro plasma. Latency on my PS4 and XO (also via the amp) is negligible. With providence though, it's severe. I'm fairly well versed in retro gaming, and the latency associated with analogue to HDMI upscalers.  I'd say the latency I'm seeing in Providence is similar, so around the 120ms mark. It makes games which require quick responses impossible to play.  

Trying other Apple TV games with the Horipad, such as Rayman and Transistor, I see some lag, certainly more than with the PS4 or XO, but crucially much less than with Providence. 

With regard to the OpenEmu source from which Providence was drawn, I use that often on my iMac with a wired USB Saturn pad, and there's no perceptible latency.

**Comment by jasarien** [comment]
It's Provenance, not Providence.

**Comment by sakuranbokun** [comment]
Apologies. No offense intended. Provenance is amazing piece of work, thanks for putting it together.  I almost bought a Shield TV for emulation, so you saved me £200. :).

**Comment by marlinmayo27** [comment]
I didn't see anyone mention making use of the Nimbus iOS app, so if someone did mention it and I missed it then I apologize.  Anyway, the reason I bring that app up is because through it you can update the controller firmware.  Curious if updating the controller firmware would help with the latency people keep experiencing.

I updated the firmware on my Nimbus last night and tested it with Provenance on my iPhone 6s Plus and the controller worked perfectly with it.  I made it a point to test faster-paced games (Mega Man 2, Sonic the Hedgehog) and had zero issues.  I haven't had a chance to test it on the Apple TV 4 since I updated the controller, but I'm going to test it out some time this week.  

Either way, it probably wouldn't hurt to update your Nimbus controllers for those of you who have one.  I'd assume it improves the functionality.

**Comment by pjpalomaki** [comment]
I updated my Nimbus firmware via the app the moment I got so it's running the latest version and still experiencing some lag with Provenance on ATV. That said, it's almost imperceptible and Provenance is already a great app on ATV!

**Comment by sakuranbokun** [comment]
I got a second Horipad today and paired it with my second ATV 4. This one is connected direct to a Samsung LED TV, which are famous for having low levels of latency. Sadly I still see a good deal of latency with Provenance vs my other set-up with the Pioneer plasma and AV amp. It may be slightly better, but not much. 

Maybe the Horipads are slow... who knows, but Hori is a top end Japanese brand for controllers- they've been making pro level fighting sticks for decades - , so if that were the case it would be surprising.

**Comment by jamiecruickshank** [comment]
I also have controller input lag with an Nimbus and Stratus controller on the Apple TV. 
I have the Apple TV connected to a Samsung PC Gaming monitor and the lag is very noticeable. 
I have installed on both my iPad Air 1 and iPhone 6 Plus and there is no noticeable lag with either controller, only on the Apple TV itself. 
I have the latest build and running the latest iOS 9.2.

**Comment by charlesvestal** [comment]
For use of actually trying to get some data around this, there's the 240p test suite, a homebrew rom which has a "manual lag" test similar to rock band's calibration. I'll run some tests with different nimbus configurations on atv vs ipad vs iphone, but hopefully this helps:
http://junkerhq.net/xrgb/index.php/240p_test_suite#Manual_Lag_Test
http://sourceforge.net/projects/testsuite240p/files/SNES_SFC/

For reference, my first test results are:
*240p Test Suite 1.0.2 // SNES*

Snes9X 1.53 // Windows // Wireless XBOX 360 Controller: 38.36 ms
Provenance 1.2.6 // Release Apple TV // Steelseries Nimbus: 118.4ms

**Comment by kwells1979** [comment]
Is this being looked into? I have the same issue (Apple TV 9.1, Provenance 1.2.6, Nimbus Controller). GameBoy Advance Mario World doesn't seem to have as much lag as the SNES version so must be down to the individual emulator?

**Comment by atv4user** [comment]
(Apple TV 4, Provenance 1.2.6, Nimbus Controller, HDMI to TV) 
I noticed a big difference in latency once I updated the nimbus controller firmware to v1.6.4.1
Very noticable with NES Super Mario World, went from unplayable to almost unnoticeable.
Make sure you get the nimbus companion app.
https://itunes.apple.com/app/steelseries-nimbus-companion/id1039561905?mt=8

**Comment by tmolling** [comment]
I've actually had 1.6.4.1 on my nimbus two months ago and had latency issues all the time.

**Comment by amsennet** [comment]
Any ideas on why my nimbus controller would be disconnecting from both aTV and iPad while playing in provenance? The controller works great in other games on both devices but disconnects after a few minutes in provenance. I'm on the latest iOS version, app version, and controller firmware. Also after it disconnects the only way to get the controller back on it to plug in the charge cable. It is fully charged though. Bad controller? Works fine in App Store apps though.

**Comment by appletv4** [comment]
Anybody try the new TVOS beta 9.2 
Maybe that helps

**Comment by DanielFontes** [comment]
@appletv4 Nope, i think it is still the same. I got iCade working but it is too laggy with tvOS 9.2

**Comment by niltz** [comment]
@jasarien I'm experiencing lag with Apple TV 4 tvOS 9.1, Provenance 1.2.6, and the Nimbus controller (with firmware 1.6.4.1) on a Samsung 1080p smart tv. I would love to help debug this in any way I can. I'm not sure where I could put log messages or whatnot, but if you let me know what to do (or provide a branch with log messages that would help) I would be happy to run it and provide the logs. I've noticed the lag in SNES games, as well in NES games (though not as much).

**Comment by mikeyg19** [comment]
@niltz I have the exact same setup (TV, versions, etc) and have the same lag problems. Most games are playable but games like Mario (NES), it's just enough to throw off the timing, making the game hard to play. 

iOS games seem to have no lag at all with the Nimbus controller.

**Comment by coreyfloyd** [comment]
I also have been experiencing this lag. As @mikeyg19 noted, it's enough to make many games, like Mario, unplayable. 

Has anyone been able to fix it?

**Comment by mazerati** [comment]
Hello,
Just joined the forum because I was having this same issue but fixed it simply by putting my TV into Game Mode. I have Provenance 1.2.6 sideloaded on my 32GB Apple TV with a Vizio M50-C1 4KTV, I am also using the MFi Nimbus Steelseries controller. When playing games like SNES Super Mario World, there was a definite lag between when the button is pressed to when the action happens. Like when I press A to jump, Mario will jump a few milliseconds late. This did indeed make the game very difficult to play. After trying Game Mode, it fixed the lag. So remember, Game Mode in your TV's settings is your friend.

**Comment by drcreek** [comment]
I did have a lot of lag with game mode. But I will resideload it this week and report back if anything has changed since December. If anyone's else used to have issues please kindly do the same. It would be interesting to find out if much has changed. 

DMx

**Comment by seanbperiod** [comment]
There are times when the lag would be so much that I'd have to close out
the app. The lag is much less noticeable on first load. But when I've left
just the app open with no game loaded, the interface was sluggish, and the
lag was MUCH worse until I closed out the app.



*Sean Burdick  Web & Graphics Designer|seanburdick.com
<http://seanburdick.com/>607.341.4349 *

**Comment by turbineseaplane** [comment]
I have this exact issue also - Running the Provenance 1.2.6 on my Apple TV 4th Gen 32GB.

Running the latest Provenance on my iPad Pro using the Horipad Ultimate, there is no latency with button presses at all in Super Mario All Stars + World (SNES).  Exact same controller + Game on the Apple TV version and the delay on the button presses makes it unplayable really.

The controller works superbly with all normal iOS apps (like Sonic, Sonic 2, Sonic CD) and also with Provenance on iOS.

Something is up with using it on tvOS though.

Major bummer - Hope it can be rectified.
Thank you all for your hard work on this app!  Great stuff!!

**Comment by apexad** [comment]
I'm sorry for asking this question, but you are using ProvenanceTV-Release not, ProvenanceTV, right?

**Comment by tonycoco** [comment]
I experienced this last night. Fresh ATV4, brand new Nimbus MFI controller, game mode ON new 4k Vizio TV, fresh build of ProvenanceTV-Release.

Super Mario is near unplayable with jumps not working 1/2 the time.

**Comment by graphicbryan** [comment]
Did you update the firmware on your Nimbus MFI controller?

**Comment by tonycoco** [comment]
@graphicbryan Does that actually help?

**Comment by whitverj** [comment]
@tonycoco Unlikely.  From all appearances, the issue is in the time it takes to process the controller's input and apply it to the emulator core, not in the time it takes the controller to send the input to the AppleTV.  For some reason, the issue is only present on AppleTV, not on any other platforms where Provenance runs.  But because no one can (or has bothered to) gather hard, reproducible data about where exactly the lag is happening, @jasarien can't (or won't) investigate a fix.

**Comment by lolkthxbai** [comment]
@tonycoco yes, it does. When I first bought the ATV and Nimbus Controller I was disappointed with the amount of lag between button presses but when I paired the controller with my phone it recommended I install the app and the app has a firmware update feature. I updated it and since then I've had no lag at all.

**Comment by whitverj** [comment]
@lolkthxbai I suppose it's possible -- but consider that many people in this thread have said that the lag they experience is inconsistent.  Sometimes it's very noticeable, sometimes it seems not-so-bad.  It's possible that the firmware update helped (I'll try again tonight after making sure my firmware is up-to-date), but it's also possible that you just ran into a not-so-bad run that just happened to fall after the firmware update.  

Let's hope it's the former, because having everyone update their controller's firmware is a much easier fix than any other solution (since there appear to be none forthcoming).

**Comment by jyc66** [comment]
Be sure to load the app as a Release build and not a debug build.

**Comment by whitverj** [comment]
@jyc66 Yeah, thanks - I know how to do that.  I only ever run release builds, not debug.

**Comment by seanbperiod** [comment]
Alright guys. I have  SteelSeries XL and after some hunting I found a USB port and updated the firmware. and WOW. it helped IMMENSELY! I still notice like a "hair" of lag, but mario is definitely 90% more playable now. So everyone. Update your firmwares (your controllers, not your aTVs :D )

**Comment by charlesvestal** [comment]
Is no one else interested in submitting data from 240p? It certainly appears the lag is there, measurable and repeatable.

**Comment by lolkthxbai** [comment]
@charlesvestal I don't mind. Like I said before, I updated the controller firmware, am running a release build that was compiled about a week ago. When I play Aladdin on SNES the right shoulder button work intermittently or lags. Other times, it just doesn't work at all. In all games there's a split second of lag between button presses. I thought the nimbus was to blame but when I play oceanhorn and transistor it works fine. I can submit any diagnostic data neccessary. Tell me what to do to capture it and I'll submit it.

**Comment by charlesvestal** [comment]
@lolkthxbai awesome. I linked to the 240p test suite rom, if you want to try the manual lag test above. https://github.com/jasarien/Provenance/issues/157#issuecomment-168223906

**Comment by JoeMatt** [comment]
I made a tweak to the NES emu to switch MFI polling to before the emulator runs a cycle similar to a tweak that was made in the SNES in this ticket https://github.com/jasarien/Provenance/issues/354

**Comment by drakkhen** [comment]
Just wanted to thank you all for resolving this!  I didn't get a chance to rebuild/install on my AppleTV 4 until today and NES Zelda II is MUCH better.  Cheers!

**Comment by mattstoker** [comment]
I was disappointed with input lag on a new ATV4 and Horipad controller playing Super Mario Bros on SNES on my Vizio 4k TV. Nearly unplayable. However, after I turned on the setting on the TV's menu for game latency reduction, the situation was drastically improved. There is a bit of latency (I notice it on on the menu and Sonic the Hedgehog native app), but it is very playable now.

**Comment by alexchandel** [comment]
**PSA to future readers: turn off Dolby Vision (/ turn on your TV's Game Mode) when using Provenance.**

**Comment by JoeMatt** [comment]
> PSA to future readers: turn off Dolby Vision (/ turn on your TV's Game Mode) when using Provenance.

thanks, added this to the wiki FAQ.
